### ISSUE TITLE
Nested Sub Categories

### ISSUE THREAD

**Issue by samberrry** [LukasMarkevicius/laravel-tutorial#3]
Hi Lukas, thanks for your useful code.. what is your solution for nested categories? for example category hierarchy with 4 levels not only 2 levels

many thanks

**Comment by LukasMarkevicius** [comment]
Hey @vhessam,

Sorry for such a late response, apparently Github doesn't notify by default when someone opens an issue or maybe I somehow missed it 🙈

If it's still relevant to you, you could apply the same logic to the multi level category hierarchy. Because even the second level subcategory still has a relationship with other categories whose ID matches parent_id. So basically everything is there, you would just need to update 'create' form to allow input for multi level category hierarchy and update the view template to display accordingly.

**Comment by samberrry** [comment]
Do you believe that I do not remember what I said :)))
But it's ok :D
